# Site settings
author: Gina
title: TheGinaStruggles
header-img: img/home-bg.png
email: ginafedder@yahoo.com
copyright_name: Gina
description: > # this means to ignore newlines until "baseurl:"
  A snippet of my path to becoming a full blown web developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lafesh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
